ARG ALPINE_TAG=latest
FROM arm32v5/debian:${ALPINE_TAG}

LABEL maintainer="Matthias Konrath" \
    description="Mikrotik tor Container"

### Download software
RUN apt update && apt install tor nano -y

### Change config to allow all connections to the tor server
RUN echo "SOCKSPort 0.0.0.0:9050" >> /etc/tor/torrc


ENTRYPOINT ["/usr/bin/tor"]
